excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://revistapiattelli.github.io
title: Revista Piattelli
tagline: A day in the life of winemakers
description: we love what we do so you can too
paginate: 20
